<?php

namespace Database\Seeders;

use Database\Factories\FootballFactory;
use App\Models\football;
use Illuminate\Database\Seeder;

class FootballSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $teams = [
           ['team'=>'Manchester City',
               'team_id'=>1001,
               'league_id'=>1,
               'points'=>77,
               'wins'=>24,
               'draws'=>5,
               'losses'=>4,
               'gd'=>45,
               'sport_id'=>1,
               'img_name'=>'manCity.png'],
           ['team'=>'Manchester United',
               'team_id'=>1002,
               'league_id'=>1,
               'points'=>67,
               'wins'=>19,
               'draws'=>10,
               'losses'=>4,
               'gd'=>29,
               'sport_id'=>1,
               'img_name'=>'manUtd.png'],
           ['team'=>'Leicester City',
               'team_id'=>1003,
               'league_id'=>1,
               'points'=>62,
               'wins'=>19,
               'draws'=>5,
               'losses'=>9,
               'gd'=>22,
               'sport_id'=>1,
               'img_name'=>'leicesterCity.png'],
           ['team'=>'Chelsea',
               'team_id'=>1004,
               'league_id'=>1,
               'points'=>58,
               'wins'=>16,
               'draws'=>10,
               'losses'=>7,
               'gd'=>20,
               'sport_id'=>1,
               'img_name'=>'chelsea.png'],
           ['team'=>'West Ham',
               'team_id'=>1005,
               'league_id'=>1,
               'points'=>55,
               'wins'=>16,
               'draws'=>7,
               'losses'=>10,
               'gd'=>10,
               'sport_id'=>1,
               'img_name'=>'westHam.png'],
           ['team'=>'Liverpool',
               'team_id'=>1006,
               'league_id'=>1,
               'points'=>54,
               'wins'=>15,
               'draws'=>9,
               'losses'=>9,
               'gd'=>16,
               'sport_id'=>1,
               'img_name'=>'liverpool.png'],
           ['team'=>'Tottenham',
               'team_id'=>1007,
               'league_id'=>1,
               'points'=>53,
               'wins'=>15,
               'draws'=>8,
               'losses'=>10,
               'gd'=>18,
               'sport_id'=>1,
               'img_name'=>'tottenham.png'],
           ['team'=>'Everton',
               'team_id'=>1008,
               'league_id'=>1,
               'points'=>52,
               'wins'=>15,
               'draws'=>7,
               'losses'=>10,
               'gd'=>4,
               'sport_id'=>1,
               'img_name'=>'everton.png'],
           ['team'=>'Leeds United',
               'team_id'=>1009,
               'league_id'=>1,
               'points'=>47,
               'wins'=>14,
               'draws'=>5,
               'losses'=>14,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'leedsUtd.png'],
           ['team'=>'Arsenal',
               'team_id'=>1010,
               'league_id'=>1,
               'points'=>46,
               'wins'=>13,
               'draws'=>7,
               'losses'=>13,
               'gd'=>7,
               'sport_id'=>1,
               'img_name'=>'arsenal.png'],
           ['team'=>'Aston Villa',
               'team_id'=>1011,
               'league_id'=>1,
               'points'=>45,
               'wins'=>13,
               'draws'=>6,
               'losses'=>13,
               'gd'=>9,
               'sport_id'=>1,
               'img_name'=>'astonVilla.png'],
           ['team'=>'Wolves',
               'team_id'=>1012,
               'league_id'=>1,
               'points'=>41,
               'wins'=>11,
               'draws'=>8,
               'losses'=>14,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'wolves.png'],
           ['team'=>'Crystal Palace',
               'team_id'=>1013,
               'league_id'=>1,
               'points'=>38,
               'wins'=>10,
               'draws'=>8,
               'losses'=>14,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'crystalPalace.png'],
           ['team'=>'Burnley',
               'team_id'=>1014,
               'league_id'=>1,
               'points'=>36,
               'wins'=>9,
               'draws'=>9,
               'losses'=>15,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'burnley.png'],
           ['team'=>'Southampton',
               'team_id'=>1015,
               'league_id'=>1,
               'points'=>36,
               'wins'=>10,
               'draws'=>6,
               'losses'=>16,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'southampton.png'],
           ['team'=>'Newcastle',
               'team_id'=>1016,
               'league_id'=>1,
               'points'=>36,
               'wins'=>9,
               'draws'=>9,
               'losses'=>15,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'newcastle.png'],
           ['team'=>'Brighton',
               'team_id'=>1017,
               'league_id'=>1,
               'points'=>34,
               'wins'=>7,
               'draws'=>13,
               'losses'=>13,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'brighton.png'],
           ['team'=>'Fullham',
               'team_id'=>1018,
               'league_id'=>1,
               'points'=>27,
               'wins'=>5,
               'draws'=>10,
               'losses'=>18,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'fullham.png'],
           ['team'=>'West Brom',
               'team_id'=>1019,
               'league_id'=>1,
               'points'=>25,
               'wins'=>5,
               'draws'=>10,
               'losses'=>18,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'westBrom.png'],
           ['team'=>'Sheffield United',
               'team_id'=>1020,
               'league_id'=>1,
               'points'=>17,
               'wins'=>5,
               'draws'=>2,
               'losses'=>26,
               'gd'=>0,
               'sport_id'=>1,
               'img_name'=>'sheffieldUtd.png'],
       ];

      foreach($teams as $team){
          football::create([
              'team'=> $team['team'],
              'team_id'=> $team['team_id'],
              'league_id'=> $team['league_id'],
              'points'=> $team['points'],
              'wins'=> $team['wins'],
              'draws'=> $team['draws'],
              'losses'=> $team['losses'],
              'gd'=> $team['gd'],
              'sport_id'=> $team['sport_id'],
              'img_name'=>$team['img_name']
          ]);
      }
    }
}
